using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1003:Use generic event handler instances", Justification = "Subscribers only need a re-render ping, not event args.", Scope = "member", Target = "~E:MtgCsvHelper.BlazorWebAssembly.ICatalogLoader.StateChanged")]
[assembly: SuppressMessage("Design", "CA1003:Use generic event handler instances", Justification = "Subscribers only need a re-render ping, not event args.", Scope = "member", Target = "~E:MtgCsvHelper.BlazorWebAssembly.CatalogLoader.StateChanged")]
[assembly: SuppressMessage("Design", "CA1055:URI-like return values should not be strings", Justification = "Consumed by MudImage.Src and anchor hrefs, which take string.", Scope = "member", Target = "~M:MtgCsvHelper.BlazorWebAssembly.ScryfallImage.Url(System.Guid)~System.String")]
[assembly: SuppressMessage("Design", "CA1055:URI-like return values should not be strings", Justification = "Consumed by MudImage.Src and anchor hrefs, which take string.", Scope = "member", Target = "~M:MtgCsvHelper.BlazorWebAssembly.ScryfallImage.CardPageUrl(System.String,System.String)~System.String")]
[assembly: SuppressMessage("Design", "CA1055:URI-like return values should not be strings", Justification = "Consumed by MudImage.Src and anchor hrefs, which take string.", Scope = "member", Target = "~M:MtgCsvHelper.BlazorWebAssembly.ScryfallImage.SetPageUrl(System.String)~System.String")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Scryfall URLs use lowercase set codes by convention.", Scope = "member", Target = "~M:MtgCsvHelper.BlazorWebAssembly.ScryfallImage.CardPageUrl(System.String,System.String)~System.String")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Scryfall URLs use lowercase set codes by convention.", Scope = "member", Target = "~M:MtgCsvHelper.BlazorWebAssembly.ScryfallImage.SetPageUrl(System.String)~System.String")]
